### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by thedagnode** [ArhasGH/PySide2-Collapsible-Widget#1]
Hi. Not sure if this is ok to post here, but thought to give it a try because I really liked what you done.
I'm using Maya 2020 so not sure if that might be the problem. But this is what I get. The container expands weirdly
https://imgur.com/a/ytTR8PP

here's my test code:

```
import sys
from PySide2 import QtGui, QtWidgets
import Container

# Create main application window
if not QtWidgets.QApplication.instance():
    app = QtWidgets.QApplication(sys.argv)
else:
    app = QtWidgets.QApplication.instance()
        
wid = QtWidgets.QWidget()
wid.resize(250, 150)
wid.setWindowTitle('Simple')

layout = QtWidgets.QHBoxLayout(wid)
container = Container.Container("Group")
layout.addWidget(container)
content_layout = QtWidgets.QGridLayout(container.contentWidget)

content_layout.addWidget(QtWidgets.QPushButton("Button"))


wid.show()
```

**Comment by aronamao** [comment]
Try adding a spacer (QtWidgets.QSpacerItem) at the bottom. Qt starts to override scaling settings when there aren't enough widgets present.

**Comment by thedagnode** [comment]
Oh, that was fast. Thank you. Will try it tomorrow!

**Comment by thedagnode** [comment]
Ended up trying it on my laptop in the cmd.exe
Tried to do as per your instructions, but it will not work on my end. Here I'm using Python 3 with Pyside2. Tested by adding both a QSpacerItem in the container and a spacerItem in the mainLayout(QGridLayout)

```
import sys
from PySide2 import QtGui, QtWidgets
import Container

# Create main application window
app = QtWidgets.QApplication(sys.argv)
mainWin = QtWidgets.QWidget()
mainWin.resize(300, 400)
mainWin.setWindowTitle("PySide2 UI")


mainLayout = QtWidgets.QGridLayout(mainWin)
container = Container.Container("Group")

mainLayout.addWidget(container)
content_layout = QtWidgets.QVBoxLayout(container.contentWidget)
content_layout.addWidget(QtWidgets.QPushButton("Button"))

spaceItem = QtWidgets.QSpacerItem( 10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
content_layout.addSpacerItem(spaceItem)
mainLayout.spacerItem()

mainWin.show()
app.exec_()
```

If you by any chance could share what your code looks like for the image you did?

**Comment by aronamao** [comment]
Sorry for the late reply, I forgot to mention that you have to make sure the last row containing the spacer is actually able to stretch. `QVBoxLayout.setStretch(last_index, True)` / `QGridLayout.setRowStretch(last_index, True)`. I am not quite sure why this has to be specified for it to not stretch the other widgets, but so be it.

**Comment by aronamao** [comment]
> 

```
# Create main application window
if not QtWidgets.QApplication.instance():
    app = QtWidgets.QApplication(sys.argv)
else:
    app = QtWidgets.QApplication.instance()
        
wid = QtWidgets.QWidget()
wid.resize(250, 150)
wid.setWindowTitle('Simple')

layout = QtWidgets.QVBoxLayout(wid)
container = Container.Container("Group")
layout.addWidget(container)
content_layout = QtWidgets.QGridLayout(container.contentWidget)

content_layout.addWidget(QtWidgets.QPushButton("Button"))

layout.addItem(QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding))
layout.setStretch(1, 1)

wid.show()
```

This should be the working code for that

**Comment by thedagnode** [comment]
Oh wow, thank you!
That's great! Looks really great. Good work! =)

**Comment by thedagnode** [comment]
Btw, do you by any chance know if there's a way to resize the UI when collapsing the UI again?

**Comment by aronamao** [comment]
> Oh wow, thank you! That's great! Looks really great. Good work! =)

Thank you!

> Btw, do you by any chance know if there's a way to resize the UI when collapsing the UI again?

As in the entire window readjusting to it's contents?
There's no built in way to do so as far as I am aware of. You need to override the events that cause the content size to change and then call the appropriate methods like resize.

**Comment by thedagnode** [comment]
Yes, exactly. So it's resizing to a smaller window after the dropdown layout has been closed.
I've worked on PyQt the whole day and learned a lot, but I feel there are irritating bugs like this one that you have to add an empty widget at the end. Like, what?!
And I've been working on doing a collapsable layout of my own and try to make it work with stylesheet, but coudn't really.
Here's an attempt anyway. :)

https://file.io/upc4KdOOnIuX
